const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
const START_GAME = 'START_GAME';
const SHOW_ANSWER = 'SHOW_ANSWER';
const PLAY_AGAIN = 'PLAY_AGAIN';
const API =
  'https://opentdb.com/api.php?amount=10&difficulty=hard&type=boolean';

export default {
  REQUEST_QUESTIONS,
  RECEIVE_QUESTIONS,
  SET_ACTIVE_QUESTION,
  START_GAME,
  SHOW_ANSWER,
  PLAY_AGAIN,
  API
};
